name: tick1

services:
  influxdb:
    image: influxdb:1.8
    container_name: tick-influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./tick-1/influxdb:/var/lib/influxdb
      - ./tick-1/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./tick-1/influxdb/init:/docker-entrypoint-initdb.d:ro
    environment:
      INFLUXDB_DB: telegraf
    networks:
      - cms-shared-net

  chronograf:
    image: chronograf:1.10
    container_name: tick-chronograf
    ports:
      - "8888:8888"
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
      RESOURCES_PATH: /var/lib/chronograf/resources
    depends_on:
      - influxdb
      - kapacitor
    volumes:
      - ./tick-1/chronograf:/var/lib/chronograf
      - ./tick-1/chronograf/resources:/var/lib/chronograf/resources
    networks:
      - cms-shared-net

  kapacitor:
    image: kapacitor:1.6
    container_name: tick-kapacitor
    ports:
      - "9092:9092"
    environment:
      KAPACITOR_INFLUXDB_0_ENABLED: "true"
      KAPACITOR_INFLUXDB_0_DEFAULT: "true"
      KAPACITOR_INFLUXDB_0_NAME: influxdb
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    depends_on:
      - influxdb
    volumes:
      - ./tick-1/kapacitor:/var/lib/kapacitor
      - ./tick-1/kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
      - ./tick-1/kapacitor/tasks:/etc/kapacitor/load:ro
    networks:
      - cms-shared-net

  telegraf:
    image: telegraf:1.30
    container_name: tick-telegraf
    user: root
    environment:
      HOST_PROC: /host/proc
      HOST_SYS: /host/sys
      HOST_ETC: /hostfs/etc
    volumes:
      - ./tick-1/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/hostfs:ro
    networks:
      - cms-shared-net

networks:
  cms-shared-net:
    external: true
