Plugins.PostgreSQL.Sessions.cmspostgres.Uri=tcp://cms-postgres:5432
Plugins.PostgreSQL.Sessions.cmspostgres.User=zbx_monitor
Plugins.PostgreSQL.Sessions.cmspostgres.Password=zabbix_pwd_mon
Plugins.PostgreSQL.Sessions.cmspostgres.Database=postgres
