is_master = true
node_id_file = /usr/share/graylog/data/config/node-id
password_secret = CHANGE_ME_TO_A_LONG_RANDOM_SECRET
root_password_sha2 = PUT_SHA256_OF_ADMIN_PASSWORD_HERE
http_bind_address = 0.0.0.0:9000
http_external_uri = http://GRAYLOG_VM2_IP:9000/
mongodb_uri = mongodb://mongodb:27017/graylog
elasticsearch_hosts = http://opensearch:9200
message_journal_enabled = true
