[SERVICE]
    Flush       5
    Daemon      Off
    Log_Level   info
    HTTP_Server Off

[INPUT]
    Name              tail
    Path              /logs/nginx/*.log
    Path_Key          file
    Tag               nginx
    Read_From_Head    On
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On
    Buffer_Chunk_Size 32k
    Buffer_Max_Size   64k

[INPUT]
    Name              tail
    Path              /logs/php-fpm/*.log
    Path_Key          file
    Tag               php-fpm
    Read_From_Head    On
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On
    Buffer_Chunk_Size 32k
    Buffer_Max_Size   64k

[INPUT]
    Name              tail
    Path              /logs/postgresql/*.log
    Path_Key          file
    Tag               postgresql
    Read_From_Head    On
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On
    Buffer_Chunk_Size 32k
    Buffer_Max_Size   64k

[OUTPUT]
    Name              loki
    Match             nginx
    Host              loki
    Port              3100
    Labels            job=nginx,source=fluent-bit

[OUTPUT]
    Name              loki
    Match             php-fpm
    Host              loki
    Port              3100
    Labels            job=php-fpm,source=fluent-bit

[OUTPUT]
    Name              loki
    Match             postgresql
    Host              loki
    Port              3100
    Labels            job=postgresql,source=fluent-bit
