[www]
user = www-data
group = www-data
listen = 9000
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

pm.status_path = /fpm-status
ping.path = /ping
ping.response = pong
catch_workers_output = yes

access.log = /var/log/php-fpm/$pool.access.log
access.format = "%R -%t \"%m %r%Q%q\" %s %{mili}d %{kilo}M %C%%"

php_admin_value[error_log] = /var/log/php-fpm/$pool.error.log
php_admin_flag[log_errors] = on
slowlog = /var/log/php-fpm/$pool.slow.log
request_slowlog_timeout = 5s
